# Generated by Django 5.1.7 on 2025-03-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание')),
                ('salary', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Зарплата')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-created_date'],
            },
        ),
    ]
